rook-ceph:
  monitoring:
    enabled: true
rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  cephClusterSpec:
    cephVersion:
      imagePullPolicy: IfNotPresent
    cephConfig:
      osd:
        bluestore_slow_ops_warn_threshold: "15"
    mon:
      count: 1
    mgr:
      count: 1
    dashboard:
      ssl: false
    logCollector:
      enabled: false
    removeOSDsIfOutAndSafeToRemove: true
    resources:
      osd:
        limits:
          memory: 4Gi # rule of thumb for ceph osd memory: 1Gi per 1TB of storage
        requests:
          cpu: 100m
          memory: 4Gi
  cephBlockPools:
    - name: builtin-mgr
      spec:
        name: .mgr
        failureDomain: osd
        replicated:
          size: 2
      storageClass:
        enabled: false
    - name: standard-rwo
      spec:
        failureDomain: osd
        replicated:
          size: 2
      storageClass:
        enabled: true
        name: standard-rwo
        isDefault: true
        allowVolumeExpansion: true
        parameters:
          imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    isDefault: true
  cephFileSystems:
    - name: standard-rwx
      spec:
        metadataPool:
          failureDomain: osd
          replicated:
            size: 2
        dataPools:
          - name: data0
            failureDomain: osd
            replicated:
              size: 2
        metadataServer:
          activeCount: 1
          activeStandby: false
          priorityClassName: system-cluster-critical
      storageClass:
        enabled: true
        name: standard-rwx
        isDefault: false
        allowVolumeExpansion: true
        pool: data0
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephFileSystemVolumeSnapshotClass:
    enabled: true
    isDefault: false
  cephObjectStores: []
