renovate:
  cronjob:
    schedule: '0 9 * * *'  # Everyday at 09:00
  renovate:
    config: |
      {
        "platform": "github",
        "repositories": ["meyeringh/homelab", "meyeringh/cf-switch"],
        "automerge": true,
        "automergeType": "branch",
        "ignoreTests": true,
        "packageRules": [
          {
            "matchUpdateTypes": ["major"],
            "automerge": false
          }
        ]
      }
  existingSecret: renovate-secret
