app-template:
  controllers:
    meyeringh-org:
      pod:
        securityContext:
          fsGroup: 101
      containers:
        nginx:
          image:
            repository: nginxinc/nginx-unprivileged
            tag: stable-alpine3.21
        git-sync:
          image:
            repository: registry.k8s.io/git-sync/git-sync
            tag: v4.6.0
          args:
            - "--repo=https://github.com/meyeringh/meyeringh-org"
            - "--ref=HEAD"
            - "--depth=1"
            - "--root=/usr/share/nginx"
            - "--link=/usr/share/nginx/html"
            - "--period=1m"
  service:
    nginx:
      controller: meyeringh-org
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: &host meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: nginx
                port: 8080
      tls:
        - hosts:
            - *host
          secretName: meyeringh-org-tls-certificate
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: "standard-rwx"
      size: 1Gi
      retain: true
      advancedMounts:
        meyeringh-org:
          nginx:
            - path: /usr/share/nginx
              subPath: content
          git-sync:
            - path: /usr/share/nginx
              subPath: content