# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.nextcloud
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.paperless
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.webtrees
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.webtrees-test
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.argocd
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.jellyfin
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.vaultwarden
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true

# Nextcloud
- name: nextcloud.nextcloud
  data:
    - key: nextcloud-password
      length: 32
      special: true
- name: nextcloud.redis
  data:
    - key: password
      length: 32
      special: true
- name: nextcloud.collabora
  data:
    - key: password
      length: 32
      special: true

# Vaultwarden
- name: vaultwarden.vaultwarden
  data:
    - key: ADMIN_TOKEN
      length: 32
      special: true

# Webtrees
- name: webtrees.webtrees
  data:
    - key: adminPassword
      length: 32
      special: false
